### PR TITLE
docs: Update to GraphQL API Documentation

### PR DESCRIPTION
**Pull request by mrcleanandfresh**
Within the last month I discovered this project and started implementing it in my own. I found the docs to be a little on the lean side, so I thought I would contribute to them.

I added an example of how to authenticate with a service using GraphQL. I used most of the information [from this code](https://github.com/accounts-js/accounts/blob/220566425755a7015569d8e518095701ff7122e2/packages/graphql-api/src/modules/accounts/schema/types.ts). I was not sure of the "official" `serviceName` for each one of them though. 

I would also like to add additional information for each of the services, but am not sure what content to write, or if it should be organized differently. So this is my _first draft_ so to say. Please offer any feedback that would be helpful to fill out these docs a little more.

### CODE REVIEW

**Comment by pradel** [comment]
Improving the documentation is definitely needed!
The update looks amazing, maybe you could add the same to the website documentation too what do you think?

**Comment by mrclean-oa** [comment]
>  maybe you could add the same to the website documentation too what do you think?

Absolutely! Can you point me in the right direction, so I can make that update? I didn't realize there were two places that needed updating. Anything I should know when updating the website docs?

**Comment by pradel** [comment]
All the website docs are located there https://github.com/accounts-js/accounts/tree/master/website/docs
Nothing in particular, we are using docusaurus and the website is there https://www.accountsjs.com/

**Comment by mrcleanandfresh** [comment]
I've never used docusaurus so let me know if this is resolved in f1483c0. Didn't know how it determined when to start a new page, since I noticed the graphql.md file had both server and client in it.

**Comment by pradel** [comment]
Looks great like this!

**Pull request merged**
