### PR TITLE
Made access token optional when calling getUser with graphql

### PR DESCRIPTION
**Pull request by elie222**

### CODE REVIEW

**Comment by pradel** [comment]
Maybe for this one it makes sense to just remove the parameter what do you think?

**Comment by elie222** [comment]
Could be. I figured I'd touch it as little as possible and still give
people the previous option if it was needed. But I'm happy to remove it as
well.

Elie

**Comment by pradel** [comment]
If you can remove them would be super cool. The other logged in mutations (eg change password) require you to send the token via headers and do not accept a token parameter. If we remove them it will be more consistent :)

**Comment by elie222** [comment]
Makes sense. Will remove shortly.

**Comment by elie222** [comment]
Removed.

Was also wondering if we need to send `accessToken` as an arg for these two items:

```gql
  impersonate(accessToken: String!, username: String!): ImpersonateReturn
  refreshTokens(accessToken: String!, refreshToken: String!): LoginResult
```

For `impersonate` perhaps make sense to keep? But not for refresh tokens?

**Comment by pradel** [comment]
I guess for now we can leave it like this because if we change it we have to change the rest package and test it. Can be done in another pr maybe?

**Comment by pradel** [comment]
Close #412

**Comment by TimMikeladze** [comment]
Thank you!

Published `0.3.0-beta.26`

**Pull request merged**
