### PR TITLE
Use a function for AccountsClient in apollo-link

### LINKED ISSUE #470: [HELP] How to create AccountsClient to generate the authLink required in GraphQL?
In 
https://accounts-js.netlify.com/docs/transport/graphql/#hook-it-up-to-the-apollo-client

```
import { accountsLink } from '@accounts/apollo-link';

const accountsClient = new AccountsClient( ... );
const authLink = accountsLink(accountsClient);

export const apolloClient = new ApolloClient({
  link: ApolloLink.from([authLink, httpLink]),
  cache,
});
```

What is an AccountsClient?

Is it `import { AccountsClient } from '@accounts/client';` ?
If so, what is the _accountsTransport_ required to construct AccountsClient?

### PR DESCRIPTION
**Pull request by ardatan**
Fixes #470 
Using a function will make available to handle circular imports;
```ts
accountsLink(() => accountsClient)
```

### CODE REVIEW

**Comment by pradel** [comment]
The problem to not use the client in the link is that it will not work with react-native storage or any kind of custom storage that the user can implement.

**Comment by ardatan** [comment]
How about factory function :)

**Comment by TimMikeladze** [comment]
@ardatan  I think a factory function would work. @pradel What are your thoughts?

**Comment by pradel** [comment]
@TimMikeladze @ardatan looks like this can fix our problem for now yes!

We will need to update the docs and examples before releasing a new version with this one :)

**Comment by pradel** [comment]
@ardatan can I close this one?

**Comment by ardatan** [comment]
@pradel Yes!

**Pull request closed without merging**
