### PR TITLE
feat: graphql api with graphql-module v1

### LINKED ISSUE #1079: Use graphql-modules v1 in @accounts/graphql-api
# Feature request

graphql-modules v1 is now released. We should update the graphal-api to use them, a big refactor is needed as a lot changed.

### PR DESCRIPTION
**Pull request by pradel**
Closes #1079

- [ ] Update documentation
- [ ] Update examples
- [ ] Manual testing of the previous features

### CODE REVIEW

**Comment by Akarshit** [comment]
Please let me know if I can help in any way to move this forward.

**Comment by loan-laux** [comment]
Also interested to help if I can!

**Comment by loan-laux** [comment]
Good luck with the move, @pradel!

**Comment by darkbasic** [comment]
I think I can help with this: I recently upgraded my projects to v1 and I also want to have a look at https://github.com/accounts-js/accounts/pull/1014 to see if I can make changes less drastic with v1.
If we can manage to fix those fundamental issues I will also update https://github.com/accounts-js/accounts/pull/1003 to v5 and I will finally be able to switch to accounts-js. At that point I will finally be able to put more time into this and implement the missing graphql resolvers (some strategies used to work only with the rest transport).

**Comment by pradel** [comment]
@darkbasic this sounds fantastic, feel free to ping me on slack if you need anything!

**Comment by loan-laux** [comment]
Looks like @tedraykov has made his own PR for that: https://github.com/accounts-js/accounts/pull/1147. Super excited to have this merged!

**Comment by pradel** [comment]
Closing in favor of https://github.com/accounts-js/accounts/pull/1189

**Pull request closed without merging**
