### PR TITLE
Adding Postgres/Typeorm Server Example and AntDesign Client Example.

### PR DESCRIPTION
**Pull request by agustif**
This is barely working on the server side, and definetely not working on the client side, any help or direction on how to follow, would be greatly appreciated, I don't know how to tackle #607 accountsBoost decoupling of mongo, but would love to help get it working too!

Anyway, thanks for this awesome library, and all the open-source work!

### CODE REVIEW

**Comment by agustif** [comment]
Why deleting yarn.lock fucked up the tests?

I deleted it because it had like 10.000 insertions or something like that

**Comment by agustif** [comment]
I might try to split this off into multiple branches/PR's

- typeorm-postgresql
- react-ant.design
- AccountsJS as a GraphQL-Module + PostgreSQL

I hope they help anyone like me trying to figure out from other examples done in Mongo how to make AccountsJS both work with postgreSQL thanks to the amazing typeorm plugin, and also be used as an imported module with graphql-modules.

Anyway, hope splitting into smaller-problems/examples helps it getting to master.

**Comment by pradel** [comment]
@agustif if you can split them into multiple pr's that would be great :)
I am just wondering if we really need the "react-ant.design" pr. It should be exactly the same as the material ui example no?

**Comment by agustif** [comment]
> @agustif if you can split them into multiple pr's that would be great :)
> I am just wondering if we really need the "react-ant.design" pr. It should be exactly the same as the material ui example no?
Hi Leo @pradel, thanks for the feedback! 

Well maybe we can skip that one, I'm just not a big material-ui fan, just started using it only because of it's inclusion in Accounts react example.

Maybe it shouldn't be that hard to reimplement, but it isn't at least a one-to-one implementation of just replacing Buttons and other material-ui tags for ant-design's equivalents, since they have very different API's etc, believe me it was what I first tried.

But probably  no need for it on the main repo!

Thanks again, I will push it later after cleaning up some unneeded stuff regarding ssl and timezone implementation of PRime which I copied it mostly from!

**Comment by agustif** [comment]
We can close this one down, I opened a new one only with the postgres server example: https://github.com/accounts-js/accounts/pull/689

I might prioritize the email-passwordless login over the ant.design implementation, I'm growing fond of Material-UI anyway and now that v4 has shipped I feel compelled to give it a try!

I might open a new example to use both Ant.Design and NextJS, that might be a better showcase of something else or a little more difficult to achieve than just re-doing it in react with another design lib.

**Pull request closed without merging**
