### PR TITLE
feat(graphql-client): throw a descriptive error

### LINKED ISSUE #823: graphql-client - throw error instead of generic error
If there's an error when using graphql-client and the data isn't returned, but errors are returned. This results in trying to access the result key of the undefined data object. 
Error message: `"Cannot read property 'authenticate' of undefined"`
Error stack:
```
"TypeError: Cannot read property 'authenticate' of undefined    at GraphQLClient.<anonymous> (/home/coder/project/packages/server/node_modules/@accounts/graphql-client/lib/graphql-client.js:258:40)    at step (/home/coder/project/packages/server/node_modules/tslib/tslib.js:136:27)    at Object.next (/home/coder/project/packages/server/node_modules/tslib/tslib.js:117:57)    at fulfilled (/home/coder/project/packages/server/node_modules/tslib/tslib.js:107:62)    at processTicksAndRejections (internal/process/task_queues.js:86:5)"
```

Query source line: https://github.com/accounts-js/accounts/blob/master/packages/graphql-client/src/graphql-client.ts#L201
Mutation source line: https://github.com/accounts-js/accounts/blob/master/packages/graphql-client/src/graphql-client.ts#L185

### Suggested fix

Below is a screenshot of what the result of the query is, there's an error property, so I think we should take that and throw it as an error so the caller can catch it, or at the very least get a more descriptive error message

image

### PR DESCRIPTION
**Pull request by NickBolles**
This is a proposal for how to throw messages..

Before, data would be undefined and we would try to access the result field on data resulting in the following message:
```
  ● Accounts (e2e) › AccountsJS Client › when logged in › should login

    TypeError: Cannot read property 'tokens' of null

      at AccountsClient.<anonymous> (node_modules/@accounts/client/src/accounts-client.ts:97:35)
      at step (node_modules/tslib/tslib.js:136:27)
      at Object.next (node_modules/tslib/tslib.js:117:57)
      at fulfilled (node_modules/tslib/tslib.js:107:62)
```

After the change you get this message:
```
  ● Accounts (e2e) › AccountsJS Client › when logged in › should login

    GraphQLErrorList - 1 error in mutation: 
     mutation ($serviceName: String!, $params: AuthenticateParamsInput!) {
      authenticate(serviceName: $serviceName, params: $params) {
        sessionId
        tokens {
          refreshToken
          accessToken
        }
      }
    }
        - User not found
```

Close #823

### CODE REVIEW

**Comment by NickBolles** [comment]
I also added a fix for the following error:

```
   GraphQLErrorList - 1 errors in mutation: 
     mutation impersonate($accessToken: String!, $username: String!) {
      impersonate(accessToken: $accessToken, username: $username) {
        authorized
        tokens {
          refreshToken
          accessToken
        }
        user {
          id
          email
          username
        }
      }
    }

        - Cannot query field "email" on type "User". Did you mean "emails"?
```

**Comment by pradel** [comment]
@NickBolles that's a good idea and a better behavior thanks for this 👍 
I am just wondering if it would be better to use the default GraphqlError object?

**Comment by NickBolles** [comment]
@pradel it looks like there's a potential to have multiple errors, and it's not possible to throw multiple errors, so I made a wrapper for it and let the consumer have access to the raw list of errors via the `errors` property. I'm up for figuring out a better way though!

**Comment by NickBolles** [comment]
@pradel should we check if there's only one error and throw that error by itself, otherwise throw the errorList?

**Comment by pradel** [comment]
@NickBolles I think it's fine that way :) do you think you could add an example of how to handle the error in the graphql documentation? `website/docs/transports/graphql.md`

**Comment by NickBolles** [comment]
sorry that took so long, I didn't see your response till now. Just added a little blurb about it. Let me know if you think it needs any changes. 

While I was at it I updated the example to be more accurate (at least in my experience)

**Comment by pradel** [comment]
@NickBolles sorry I didn't get back to it earlier. Can you please resolve the conflicts you have so I can merge it? :)

**Comment by NickBolles** [comment]
@pradel done!

**Comment by pradel** [comment]
@NickBolles looks like the tests are failing, can you please take a look?

**Comment by NickBolles** [comment]
@pradel that should be fixed now. Sorry for the huge delay

**Comment by pradel** [comment]
Thank you @NickBolles!

**Pull request merged**
