### PR TITLE
fix: typeorm example fixes

### PR DESCRIPTION
**Pull request by darkbasic**
Make typeorm server working out of the box

### CODE REVIEW

**Comment by agustif** [comment]
I was thinking about dropping docker for the postgres db, and leave itto the user, could bee a nicee addo-on and be documented, but at least not have it by default on with start-servicees

**Comment by darkbasic** [comment]
@agustif I completely agree and I've just made it optional

**Comment by agustif** [comment]
@darkbasic Would you mind adding some details about both options and how to run them to the docs about postgres/typeorm?

**Comment by darkbasic** [comment]
@agustif I will give it a try but if I recall correctly documentation doesn't build anymore in current git master

**Comment by pradel** [comment]
@darkbasic the documentation should work on master, do you remember what was the issue you faced? 🤔 

For this example documentation, it should probably just be added in the README no?

**Comment by darkbasic** [comment]
@pradel the readme was already correct in that regard because it assumed that docker wasn't mandatory (which wasn't true): I simply made that assumption stand.

Anyway I rephrased it to better explain the alternatives.

Regarding the docs, I've retried to build them and it seems to work now, so no clue what could have been the problem before.

**Comment by pradel** [comment]
@darkbasic ok thanks! Can you please resolve the conflicts so I can merge? :)

**Comment by darkbasic** [comment]
@pradel I've rebased it. should merge fine now

**Pull request merged**
