### PR TITLE
impersonate take impersonatedUserId instead of username

### LINKED ISSUE #161: Impersonate should use userId instead of username
Right now the `impersonate` function takes an username in order to impersonate a user, we should use the user id instead.

### PR DESCRIPTION
**Pull request by pradel**
Close #161

### CODE REVIEW

**Comment by davidyaha** [comment]
This is actually a requirement on one of my clients because we might not have the user id at the client side. If you need the user id approach, maybe add those as options? Anyways, the user can only be impersonated when you implement the authorization method for it.

**Comment by davidyaha** [comment]
Or at least it should be the case.

**Comment by pradel** [comment]
Yeah but username should only be in the password accounts no?

**Comment by pradel** [comment]
so if you are using oauth or other you will not be able to impersonate ..

**Comment by davidyaha** [comment]
Why? Email/username are good for public identifier for any authentication strategy I would think. Just a matter of definition I guess..

**Comment by davidyaha** [comment]
I think you are correct to add the id, just think it should be an addition, along with email maybe

**Comment by davidyaha** [comment]
For instance GitHub oAuth would have a username as well as Twitter

**Comment by pradel** [comment]
If you register via oauth you can have some users without username and emails so in that case this function will not work

**Comment by pradel** [comment]
So in order to merge this one we need the accounts-password to have an impersonate function that take the username or email

**Comment by Aetherall** [comment]
Why add a impersonate function on the accounts-password ?
OAuth users can be impersonated as well
Maybe we should consider add a method like this :
````ts
function identifyUser(identity: Identity): User

interface Identity {
	userId?: string,
	username?: string,
	email?: string
}
````
So with any info of an user we can get the User object and operate

**Comment by pradel** [comment]
@davidyaha @Aetherall should be good now :)

**Pull request merged**
