### PR TITLE
Update TypeScript and fix emittery issue

### PR DESCRIPTION
**Pull request by kamilkisiela**
With TypeScript 2.9.1, current `@accounts/server` throws an error while compiling.
It's related to `emittery` package: sindresorhus/emittery/issues/34

Instead of asking a user to resolve to `emittery@0.4.0` I think `@accounts/server` should require the correct version that works fine.

Also, could it be released ASAP since it breaks apps with latest typescript?

### CODE REVIEW

**Comment by TimMikeladze** [comment]
This looks good me. I do think that `@accounts/server` should require emittery. @pradel @davidyaha @Aetherall thoughts?

**Comment by davidyaha** [comment]
@kamilkisiela  Thanks!

**Comment by davidyaha** [comment]
Published, let me know if that worked.

**Comment by kamilkisiela** [comment]
It worked, toda :+1:

**Pull request merged**
