### PR TITLE
Setup github actions

### PR DESCRIPTION
**Pull request by pradel**

### CODE REVIEW

**Comment by ozsay** [comment]
nice!

any change to include https://github.com/hipstersmoothie/jest-github-reporter in the PR? should help displaying where tests are failing

**Comment by pradel** [comment]
@ozsay interesting, maybe we can try to integrate it in another pr?

**Comment by TimMikeladze** [comment]
Yes, this looks great

**Comment by pradel** [comment]
@ozsay created an issue to keep track of it :) https://github.com/accounts-js/accounts/issues/808

**Pull request merged**
