### PR TITLE
return LoginResult from resetPassword

### PR DESCRIPTION
**Pull request by benawad**
Added this to be able to automatically login the user after reseting their password.

### CODE REVIEW

**Comment by pradel** [comment]
Hey thanks for the pr that's a good idea!
I was wondering, maybe we could have this feature enabled by an accounts-password option (boolean) rather than having it by default, what do you think?

**Comment by benawad** [comment]
sounds good

**Comment by benawad** [comment]
So if we make this opt-in what do you want to return from the mutation?  

A union?
```
union ResetPasswordResponse = LoginResult | Boolean
resetPassword(token: String!, newPassword: String!): ResetPasswordResponse
```

Return null if they don't opt-in?
```
resetPassword(token: String!, newPassword: String!): LoginResult
```

Maybe create a new mutation for it?
```
resetPasswordAndLogin(token: String!, newPassword: String!): LoginResult
```

**Comment by pradel** [comment]
I think I prefer the "Return null if they don't opt-in?" way, what do you think @TimMikeladze?

**Comment by TimMikeladze** [comment]
Agreed. Return null.

**Comment by benawad** [comment]
I made it opt-in, let me know if you would like to see any other changes

**Comment by TimMikeladze** [comment]
@benawad Thank you very much for the PR. 

Published as `0.7.0`

**Pull request merged**
