### PR TITLE
feat: release 1.0

### PR DESCRIPTION
**Pull request by darkbasic**
Closes https://github.com/accounts-js/accounts/issues/1248
Closes https://github.com/accounts-js/accounts/issues/1247
Closes https://github.com/accounts-js/accounts/issues/1244
Closes https://github.com/accounts-js/accounts/issues/1226
Closes https://github.com/accounts-js/accounts/issues/1156
Closes https://github.com/accounts-js/accounts/issues/1142
Closes https://github.com/accounts-js/accounts/issues/1034
Closes https://github.com/accounts-js/accounts/issues/816
Closes https://github.com/accounts-js/accounts/issues/768
Closes https://github.com/accounts-js/accounts/issues/632
Closes https://github.com/accounts-js/accounts/issues/627
Closes https://github.com/accounts-js/accounts/issues/607
Closes https://github.com/accounts-js/accounts/issues/483
Closes https://github.com/accounts-js/accounts/issues/466
Closes https://github.com/accounts-js/accounts/issues/404

### CODE REVIEW

**Comment by mrcleanandfresh** [comment]
Okay, looks like your example needed:

```javascript
import 'reflect-metadata';
```

At the top. I'll put that on my list.

**Comment by darkbasic** [comment]
Yes you need reflect-metadata. If something from the documentation doesn't work I suggest you to have a look at the examples folder because these get tested much more often.
Docs need to be updated to reflect some of the latest changes.

**Comment by mrcleanandfresh** [comment]
> Yes you need reflect-metadata. If something from the documentation doesn't work I suggest you to have a look at the examples folder because these get tested much more often. Docs need to be updated to reflect some of the latest changes.

Yeah, my plan is to take the documentation for a test drive and see if there are any holes in it for folks getting up and running. I was able to get up-and-running in about 30-45 minutes after some troubleshooting. So I took note of those missing elements. Most folks are going to want as little friction as possible while on-boarding. So I am keeping a list of changes I want to make to the documentation.

Good to know about the examples folder! Thanks.

Maybe we should leave comments in the open issues about the new release. I saw a very serious bug with a failed OAuth attempt that returned the first record from the users database. That's a pretty serious bug, but may be a non-issue after the re-factor? It'd be good to have the issue authors go back through after the official release to see if they are still experiencing their problems. Thoughts?

**Comment by darkbasic** [comment]
> Maybe we should leave comments in the open issues about the new release. I saw a very serious bug with a failed OAuth attempt that returned the first record from the users database. That's a pretty serious bug, but may be a non-issue after the re-factor?

Yes leave comments in the respective issues if you find anything that you can still reproduce.
I saw the OAuth one and I honestly didn't check it yet, but that's surely one that needs to be addressed before the stable release.

**Pull request merged**
