### PR TITLE
Changelog

### PR DESCRIPTION
**Pull request by TimMikeladze**

### CODE REVIEW

**Comment by pradel** [comment]
I like the idea to auto generate the changelog 🎉 
Do you know https://github.com/semantic-release/semantic-release? Maybe it can also be a good fit for this feature?

**Comment by TimMikeladze** [comment]
I looked at semantic release. Seems like Lerna already handles some of the release management stuff for us already.

**Comment by pradel** [comment]
Sounds good :) do you know if we can add the notes to the github releases with this tool?

**Comment by TimMikeladze** [comment]
I'm not sure, I think it just generates the changelog.

**Pull request closed without merging**
