### PR TITLE
Improve error messages

### PR DESCRIPTION
**Pull request by elie222**
Started making this update in the browser, but I see I need to edit more files.

I still need to add a field here:
https://github.com/accounts-js/accounts/blob/master/packages/password/src/errors.ts

`invalidUsername: 'Invalid username',`

And check/fix tests.

Fixes: https://github.com/accounts-js/accounts/issues/635

Fixes: #647

### CODE REVIEW

**Comment by Ethaan** [comment]
Do you think that, instead of `throwing` an error.

something like this, make sense?

```
type Error {
 path: String!
 message: String
}

type Response {
 ok: Boolean
 errors: [Error]
}
```
so we can do something like.

```
    const { ok } = await accountsPassword.login({
      password,
      user: {
        email,
      },
    });
```

**Comment by elie222** [comment]
If there’s an error it will throw an error in any case, no?

**Comment by pradel** [comment]
@Ethaan to get the error you can do like that:
```js
handleSubmit: async ({ email, password }, { setErrors }) => {
  try {
    const response = await accountsPassword.login({
      password,
      user: {
        email,
      },
    });
  } catch (error) {
      setError(error)
    }
},
```

**Comment by Ethaan** [comment]
Thanks @pradel!

**Comment by pradel** [comment]
Thanks for the pr @elie222 I will include it in the next release :)

**Pull request merged**
